[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "interp-macros"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "4.1.1"
quick-error = "1.2.2"
quote = "0.6.9"
syn = "0.15.18"
proc-macro2 = { version = "0.4.20", features = ["nightly"] }

[lib]
proc-macro = true
