[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "interp-macros"
version = "0.1.0"

[dependencies]
nom = "3.0.0"
quick-error = "1.2.0"
quote = "0.3.15"
syn = "0.11.11"

[lib]
proc-macro = true
